# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Change123!@#
    ports:
      - "1433:1433"


  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"


  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db

  rest:
    image: rest
    build:
      context: .
      dockerfile: Services/Rest/Rests.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStringSql=Server=database;Database=RestDb;User ID=SA;Password=Change123!@#;TrustServerCertificate=True;
      - MessageQueueConnection__host=rabbitmq
      - MessageQueueConnection__username=guest
      - MessageQueueConnection__password=guest
    ports:
      - 5212:80 #Swagger
      - 5112:443 #API

  # activity:
  #   image: activity
  #   build:
  #     context: .
  #     dockerfile: Services/Activities/Activities.Api/Dockerfile
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ConnectionStringSql=Server=database;Database=ActivityDb;User ID=SA;Password=Change123!@#;TrustServerCertificate=True;
  #     - MessageQueueConnection__host=rabbitmq
  #     - MessageQueueConnection__username=guest
  #     - MessageQueueConnection__password=guest
  #   ports:
  #     - 4212:80 #Swagger
  #     - 4112:443 #API

  # worker:
  #   image: worker
  #   build:
  #     context: .
  #     dockerfile: Services/Worker/Worker.Api/Dockerfile
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #   ports:
  #     - 6212:80 #Swagger
  #     - 6112:443 #API

  # activity-validation-result:
  #   image: activity-validation-result
  #   build:
  #     context: .
  #     dockerfile: Services/ActivityValidationResult/ActivityValidationResult.Api/Dockerfile
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - MongoDbConfig__ConnectionString=mongodb://mongodb:27017
  #     - MessageQueueConnection__host=rabbitmq
  #     - MessageQueueConnection__username=guest
  #     - MessageQueueConnection__password=guest
  #   ports:
  #     - 6212:80 #Swagger
  #     - 6112:443 #API
  #   depends_on:
  #     - mongodb
  #     - rabbitmq


  # apigatewayqueryapi:
  #   image: apigatewayqueryapi
  #   build:
  #     context: .
  #     dockerfile: ApiGateway.Queries/Dockerfile
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - activityUrl=http://activityapi:4212
  #     - restUrl=http://restapi:5212
  #     - workerUrl=http://workerapi:6212
  #   ports:
  #     - 7212:80 #Swagger
  #     - 7112:443 #API
  #   depends_on:
  #     - workerapi
  #     - activityapi
  #     - restapi

volumes:
  dbdata6:
