// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Activities.Infra;

#nullable disable

namespace Activities.Infra.Migrations
{
    [DbContext(typeof(ActivityContext))]
    [Migration("20230805183216_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Activities.Domain.Models.Entities.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAlive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("TimeActivityEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TimeActivityStart")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TimeRestEnd")
                        .HasColumnType("datetime2");

                    b.Property<byte>("TypeActivityBuild")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("Activities", (string)null);
                });

            modelBuilder.Entity("Activities.Domain.Models.Entities.Activity", b =>
                {
                    b.OwnsMany("Activities.Domain.Models.Entities.WorkActivity", "_workers", b1 =>
                        {
                            b1.Property<Guid>("ActivityId")
                                .HasColumnType("UNIQUEIDENTIFIER");

                            b1.Property<string>("WorkerId")
                                .HasColumnType("char(1)");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("ActivityId", "WorkerId");

                            b1.ToTable("WorkersActivity", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ActivityId");
                        });

                    b.Navigation("_workers");
                });
#pragma warning restore 612, 618
        }
    }
}
